### ISSUE TITLE
使用示例文件运行代码的一些报错

### ISSUE THREAD

**Issue by Birger0** [jianqingzheng/XBCR-net#1]
在下载了示例文件并按规定设置好路径后，调用语句：
```
python main_train.py --model_name XBCR_net --data_name Data_S1 --model_num 0 --max_epochs 3 --include_light 0
```
能运行完，但是并没有输出结果：

![运行train指令的结果](https://user-images.githubusercontent.com/106000466/202892846-fc974cf4-cec8-43e5-9496-9c911374b229.png)
然后再去运行infer指令：
```
python main_infer.py --model_name XBCR_net --data_name Data_S1 --model_num 0 --include_light 0
```
则是出现了如下的报错：

![运行infer的报错](https://user-images.githubusercontent.com/106000466/202893009-573f7dce-44b7-43b8-b357-a2e3ece8e29e.png)

不太清楚造成这种情况的具体原因，若能得到您的指点不胜感激

**Comment by Birger0** [comment]
我尝试全都使用默认设置来运行main_infer.py文件也出现了同样的报错。。
```
python main_infer.py
```

<img width="862" alt="df14f99c1941a0bd90fad7a58516fc9" src="https://user-images.githubusercontent.com/106000466/202992887-257d0242-bd37-4fef-83b7-cebbc9694d97.png">

IndexError: arrays used as indices must be of integer (or boolean) type
好像是数据类型不匹配的问题，请问是我的使用有什么问题么？

**Comment by jianqingzheng** [comment]
> 在下载了示例文件并按规定设置好路径后，调用语句：
> 
> ```
> python main_train.py --model_name XBCR_net --data_name Data_S1 --model_num 0 --max_epochs 3 --include_light 0
> ```
> 
> 能运行完，但是并没有输出结果：
> 
> ![运行train指令的结果](https://user-images.githubusercontent.com/106000466/202892846-fc974cf4-cec8-43e5-9496-9c911374b229.png) 然后再去运行infer指令：
> 
> ```
> python main_infer.py --model_name XBCR_net --data_name Data_S1 --model_num 0 --include_light 0
> ```
> 
> 则是出现了如下的报错：
> 
> ![运行infer的报错](https://user-images.githubusercontent.com/106000466/202893009-573f7dce-44b7-43b8-b357-a2e3ece8e29e.png)
> 
> 不太清楚造成这种情况的具体原因，若能得到您的指点不胜感激

感谢你的问题，我们代码里面“Data_S1”并不是作为“data_name”使用，我在新版本里给出了一个可以跑通的案例，希望对你有帮助。
