### ISSUE TITLE
Will it work for nanobodies?

### ISSUE THREAD

**Issue by tony-res** [jianqingzheng/XBCR-net#3]
Will this work for nanobodies?

I thought it might because of the flag `--include_light` but that option doesn't seem to have any effect. I looked at the code and can't see that it is actually used anywhere.

**Comment by jianqingzheng** [comment]
> Will this work for nanobodies?

To be honest, we have not tried this code for nanobodies. I recommend you train the network using ```train_rbd.py``` on the nanobodies dataset and then use the trained models by `infer_rbd.py` or `pred_bcr.py`.


> I thought it might because of the flag `--include_light` but that option doesn't seem to have any effect. I looked at the code and can't see that it is actually used anywhere.

this flag `--include_light` has been used in the [`train_rbd.py`](https://github.com/jianqingzheng/XBCR-net/blob/803edd2d3f62d9c83d9ba68f00ed183e562c5f31/train_rbd.py#L98), and [`infer_rbd.py`](https://github.com/jianqingzheng/XBCR-net/blob/803edd2d3f62d9c83d9ba68f00ed183e562c5f31/infer_rbd.py#L69).
It seems that I forgot make it function in `pred_bcr.py`, and I will fix it later.

**Comment by jianqingzheng** [comment]
> Will this work for nanobodies?
> 
> I thought it might because of the flag `--include_light` but that option doesn't seem to have any effect. I looked at the code and can't see that it is actually used anywhere.

Sorry for the delay in fixing it.
the flag `--include_light` has been removed from `pred_bcr.py` and now we can simply enter an empty string in `--light` to exclude the input of light chain. Thanks for your comment about this
